"""Report generators — HTML and Markdown."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, BaseLoader

from workflowbench.runner import BenchmarkRun


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

_MD_TEMPLATE = """\
# WorkflowBench Report — {{ run.run_id }}

**Adapter:** {{ run.adapter_name }}
**Timestamp:** {{ run.timestamp }}

## Summary

| Metric | Value |
|--------|-------|
| Cases | {{ run.cases_total }} |
| Passed | {{ run.cases_passed }} |
| Failed | {{ run.cases_failed }} |
| Pass rate | {{ (run.pass_rate * 100) | round(1) }}% |
| Overall score | {{ (run.overall_score * 100) | round(1) }}% |
| Total latency | {{ run.total_latency_ms | round(0) }} ms |
| Total cost | ${{ "%.4f" | format(run.total_cost_usd) }} |
| Input tokens | {{ run.total_input_tokens }} |
| Output tokens | {{ run.total_output_tokens }} |

## Per-case results

| Case | Category | Score | Pass | Completion | Escalation | Forbidden | Required | Latency |
|------|----------|-------|------|------------|------------|-----------|----------|---------|
{% for r in run.results -%}
| {{ r.case_id }} | {{ r.category }} | {{ (r.overall_score * 100) | round(1) }}% | {{ "PASS" if r.passed else "FAIL" }} | {{ (r.completion_score * 100) | round(0) }}% | {{ (r.escalation_score * 100) | round(0) }}% | {{ (r.forbidden_action_score * 100) | round(0) }}% | {{ (r.required_action_score * 100) | round(0) }}% | {{ r.latency_ms | round(0) }}ms |
{% endfor %}

{% if run.failure_clusters %}
## Failure clusters

{% for cluster, case_ids in run.failure_clusters.items() -%}
- **{{ cluster }}** ({{ case_ids | length }}): {{ case_ids | join(", ") }}
{% endfor %}
{% endif %}

---
*Generated by [WorkflowBench](https://github.com/thegeekajay/WorkflowBench)*
"""


def render_markdown(run: BenchmarkRun) -> str:
    env = Environment(loader=BaseLoader(), autoescape=False)
    template = env.from_string(_MD_TEMPLATE)
    return template.render(run=run)


def save_markdown(run: BenchmarkRun, output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"report_{run.run_id}.md"
    path.write_text(render_markdown(run))
    return path


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WorkflowBench Report — {{ run.run_id }}</title>
<style>
  :root { --pass: #22c55e; --fail: #ef4444; --bg: #f8fafc; --card: #fff; --border: #e2e8f0; --text: #1e293b; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); line-height: 1.5; padding: 2rem; max-width: 1200px; margin: auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .meta { color: #64748b; margin-bottom: 1.5rem; font-size: 0.875rem; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }
  .card .value { font-size: 1.75rem; font-weight: 700; }
  .card .label { font-size: 0.75rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
  .score-bar { height: 8px; border-radius: 4px; background: #e2e8f0; overflow: hidden; margin-top: 0.25rem; }
  .score-bar .fill { height: 100%; border-radius: 4px; }
  table { width: 100%; border-collapse: collapse; background: var(--card); border-radius: 8px; overflow: hidden; border: 1px solid var(--border); margin-bottom: 2rem; }
  th, td { padding: 0.625rem 0.75rem; text-align: left; border-bottom: 1px solid var(--border); font-size: 0.8125rem; }
  th { background: #f1f5f9; font-weight: 600; text-transform: uppercase; font-size: 0.6875rem; letter-spacing: 0.05em; }
  .badge { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.6875rem; font-weight: 600; }
  .badge-pass { background: #dcfce7; color: #166534; }
  .badge-fail { background: #fee2e2; color: #991b1b; }
  .cluster { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; margin-bottom: 0.75rem; }
  .cluster-name { font-weight: 600; margin-bottom: 0.25rem; }
  .cluster-cases { font-size: 0.8125rem; color: #64748b; }
  footer { margin-top: 2rem; text-align: center; font-size: 0.75rem; color: #94a3b8; }
  footer a { color: #3b82f6; text-decoration: none; }
</style>
</head>
<body>
<h1>WorkflowBench Report</h1>
<div class="meta">Run <strong>{{ run.run_id }}</strong> &middot; {{ run.adapter_name }} &middot; {{ run.timestamp }}</div>

<div class="cards">
  <div class="card">
    <div class="value">{{ run.cases_total }}</div>
    <div class="label">Cases</div>
  </div>
  <div class="card">
    <div class="value" style="color: var(--pass);">{{ run.cases_passed }}</div>
    <div class="label">Passed</div>
  </div>
  <div class="card">
    <div class="value" style="color: var(--fail);">{{ run.cases_failed }}</div>
    <div class="label">Failed</div>
  </div>
  <div class="card">
    <div class="value">{{ (run.pass_rate * 100) | round(1) }}%</div>
    <div class="label">Pass Rate</div>
    <div class="score-bar"><div class="fill" style="width: {{ (run.pass_rate * 100) | round(1) }}%; background: {% if run.pass_rate >= 0.7 %}var(--pass){% else %}var(--fail){% endif %};"></div></div>
  </div>
  <div class="card">
    <div class="value">{{ (run.overall_score * 100) | round(1) }}%</div>
    <div class="label">Overall Score</div>
    <div class="score-bar"><div class="fill" style="width: {{ (run.overall_score * 100) | round(1) }}%; background: {% if run.overall_score >= 0.7 %}var(--pass){% else %}var(--fail){% endif %};"></div></div>
  </div>
  <div class="card">
    <div class="value">{{ run.total_latency_ms | round(0) }}<span style="font-size:0.875rem;">ms</span></div>
    <div class="label">Total Latency</div>
  </div>
  <div class="card">
    <div class="value">${{ "%.4f" | format(run.total_cost_usd) }}</div>
    <div class="label">Total Cost</div>
  </div>
  <div class="card">
    <div class="value">{{ run.total_input_tokens + run.total_output_tokens }}</div>
    <div class="label">Total Tokens</div>
  </div>
</div>

<h2 style="margin-bottom:0.75rem;">Per-case Results</h2>
<table>
<thead>
<tr><th>Case</th><th>Category</th><th>Status</th><th>Score</th><th>Completion</th><th>Escalation</th><th>Forbidden</th><th>Required</th><th>Latency</th></tr>
</thead>
<tbody>
{% for r in run.results %}
<tr>
  <td><strong>{{ r.case_id }}</strong><br><span style="color:#64748b;font-size:0.75rem;">{{ r.case_name }}</span></td>
  <td>{{ r.category }}</td>
  <td><span class="badge {% if r.passed %}badge-pass{% else %}badge-fail{% endif %}">{{ "PASS" if r.passed else "FAIL" }}</span></td>
  <td>{{ (r.overall_score * 100) | round(1) }}%</td>
  <td>{{ (r.completion_score * 100) | round(0) }}%</td>
  <td>{{ (r.escalation_score * 100) | round(0) }}%</td>
  <td>{{ (r.forbidden_action_score * 100) | round(0) }}%</td>
  <td>{{ (r.required_action_score * 100) | round(0) }}%</td>
  <td>{{ r.latency_ms | round(0) }}ms</td>
</tr>
{% endfor %}
</tbody>
</table>

{% if run.failure_clusters %}
<h2 style="margin-bottom:0.75rem;">Failure Clusters</h2>
{% for cluster, case_ids in run.failure_clusters.items() %}
<div class="cluster">
  <div class="cluster-name">{{ cluster }} ({{ case_ids | length }})</div>
  <div class="cluster-cases">{{ case_ids | join(", ") }}</div>
</div>
{% endfor %}
{% endif %}

<footer>Generated by <a href="https://github.com/thegeekajay/WorkflowBench">WorkflowBench</a></footer>
</body>
</html>
"""


def render_html(run: BenchmarkRun) -> str:
    env = Environment(loader=BaseLoader(), autoescape=True)
    template = env.from_string(_HTML_TEMPLATE)
    return template.render(run=run)


def save_html(run: BenchmarkRun, output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"report_{run.run_id}.html"
    path.write_text(render_html(run))
    return path
